[package]
name = "yomitan-api-rs-client"
version = "0.4.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tiny_http = "0.12"
urlencoding = "2.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
