name: Create binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-11-arm]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build (macOS)
      if: matrix.os == 'macos-latest'
      run: ./platform/macos/build-app

    - name: Build (non-macOS)
      if: matrix.os != 'macos-latest'
      run: cargo build --release

    - name: Build
      run: cargo build --release
    
    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: target/release/installer
        if-no-files-found: error
    
    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          platform/macos/Yomitan API (rs) Installer.app
          platform/macos/README.txt
        if-no-files-found: error
    
    - name: Upload artifacts (Windows x86_64)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-x86_64
        path: target/release/installer.exe
        if-no-files-found: error
    
    - name: Upload artifacts (Windows arm64)
      if: matrix.os == 'windows-11-arm'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-arm64
        path: target/release/installer.exe
        if-no-files-found: error